language: ruby
rvm:
- 2.2.0
env:
  global:
    secure: UtxkLs57dG2SBdYDSCx7EjqIpflduQQ+iZ5HE6b7FsF/eSZ4Gw4jBO0D71h471t1SLEgAXN42Tp+NDh1VPs+iqE+gWY78El0TbBC4WJFO6FzJmcNWu5a/gS/IsCGcvem6GHjY0tRuAhMhSyWxAm7LTInFCsecKJthUg+z5KbI2ra4JZJRFgLNQd8L6p4bKDrji+t9BvuRWXEumWiVbnr4nxzXVlpprIuRlIipf6sPiol8jaqKhpgf7HZD3IX9X8Y9wPaW37nTJrwdSgliMUV6lr3gkBisvw5an+1d7yMRr2lGwySLyGeYPZxoABpjk7fMsydl/9Q2kQDO1dzMmbqiw0AiabVz7e8iuq1JtwaIfnCzGvCygluSCz7hxs40QwPy9xc+NieyLldUPU50izulvCUVNORLXRqFy4uYBYsKx5/iY+kk8LoM2Qr40Cl885ZdtSmGz2zfPSC8i+eWUsv9cH7B2ubCNw6arG5O/UsNxsl2w79EbJR5Wz7tZkvXWJLmwzzg2Zw30tp8AGw6jK1ti5PwskLBvewW/1iLl4JfYsJiJ1VTBTydNKIze3mFg/N00VHPTYNkRRG0WUKHVJ8amGOiqWzQKolCzakc9iAG6slqvBy0B/Jjn3FQkZghPlHHG6rlMMsX6ZtvNWNQKQ4e7xeLr4wpXXHF2qt4LokuAQ=
script:
- bundle install
- bundle exec rake package
deploy:
  provider: releases
  api_key:
    secure: r+4fjbQ6x7xI1A9SZXfQvu0iYcLIv6ny4HMQEhBKNpfHYtzqAuiha5x1h/isNAIA6l3qSsNVYxZdflRgQBatJFNfnKd8FehaojIjgjcXXVypDqtN8BGM3gMQ8MoWhDwwURr34ajtXN12Q9iHh9RVg9a3RkiOgVPAbxXw18lEF5yH7HaxESvxdlwZeuEjEMiSDNIhvSRxVCX7dy9CTiVYbyLGMixTA39YED6V/b/KgToC6P5F+a3Q81BS9r3sg89rLOtKne58ImcC7/xgUgj3471LR1uy9pxxW/26afNNfU1ITtcbdVQtLOUQGrjv5JKkCzgrbxYH6N6LYz059LLaGJnQrQ6hlSZN9Anqk/XYYmoai9g0j/7NF9VXjjIpYkgJ79Kg2zJLJ8sA3w+XJC68V+7P8oNmy9BKNtYF7nHl6aXkW4oShafIWOtv2JiofXWmaOCX/K5AIzlxkQTEDNECRY69HgZKS5MiOaCMRwX6aJlMeoXWVNj6YXB4+urmROmRQa3cIc0ewlzwRvvAXjr5d7900Rtd0/LZfa6HeaNQrgs4/SHPBpGdou0z7HBCzdxw0Cfsio5A6i4W1zkQuzM6iPq/2E4gSWXFRB4RBu94aCavEfjHPhxELPE99JRKQR8jVLYd0yYNnL6EnaA07N5Ep2Ua+cYmuEmYcYMJoauvnvg=
  file: pkg/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: pact-foundation/pact-ruby-standalone
    tags: true
after_deploy:
- "curl -X POST -H \"Authorization: Bearer ${APPVEYOR_ACCESS_TOKEN}\" -H \"Content-Type: application/json\" -d@support/pact-ruby-standalone-windows-test.json https://ci.appveyor.com/api/builds"
