name: Release

on:
  repository_dispatch:
    types:
      - gem-released

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.2.10

    - name: Set up environment
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"
        bundler -v
        bundle install

    - name: Update Gemfile
      run: script/update-in-github-workflow.sh
      env:
        RELEASED_GEM_NAME: ${{ github.event.client_payload.name }}
        RELEASED_GEM_VERSION: ${{ github.event.client_payload.version }}

    - name: Prepare release
      run: script/prepare-release-in-github-workflow.sh

    - name: Create release
      uses: ncipollo/release-action@v1
        with:
          name: pact-${{ env.VERSION }}
          tag: ${{ env.TAG }}
          artifacts: pkg/*
          bodyFile: build/RELEASE_NOTES.md
          token: ${{ secrets.GITHUB_TOKEN }}
